# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='座机'),
        ),
    ]
