# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180502_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='repository.Tag'),
        ),
    ]
