# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=100, verbose_name='标签名称')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '导航分组',
                'verbose_name_plural': '导航分组',
            },
        ),
        migrations.CreateModel(
            name='UrlInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='链接名称')),
                ('url_path', models.CharField(max_length=200, verbose_name='链接')),
                ('url_desc', models.TextField(max_length=200, verbose_name='链接描述')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('url_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='asset.UrlGroup', verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '导航详情',
                'verbose_name_plural': '导航详情',
                'ordering': ['url_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '业务线', 'verbose_name_plural': '业务线'},
        ),
        migrations.AlterModelOptions(
            name='engineroom',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': '软件', 'verbose_name_plural': '软件'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='business',
            name='caption',
            field=models.CharField(max_length=32, unique=True, verbose_name='业务线名称'),
        ),
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default='SA', max_length=32, verbose_name='业务线英文名'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='host',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Business', verbose_name='所属业务线'),
        ),
        migrations.AlterField(
            model_name='host',
            name='e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.EngineRoom', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=60, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, protocol='ipv4', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=32, verbose_name='软件名称'),
        ),
        migrations.AlterField(
            model_name='software',
            name='r',
            field=models.ManyToManyField(to='asset.Host', verbose_name='所属主机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=60, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=60, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='用户名'),
        ),
    ]
