# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180111_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='b',
        ),
        migrations.RemoveField(
            model_name='host',
            name='e',
        ),
        migrations.RemoveField(
            model_name='software',
            name='r',
        ),
        migrations.RemoveField(
            model_name='urlinfor',
            name='url_group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='EngineRoom',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='UrlGroup',
        ),
        migrations.DeleteModel(
            name='UrlInfor',
        ),
    ]
